-- Check FK
SELECT
  CONSTRAINT_SCHEMA,
  CONSTRAINT_NAME,
  UNIQUE_CONSTRAINT_SCHEMA,
  UNIQUE_CONSTRAINT_NAME,
  MATCH_OPTION,
  UPDATE_RULE,
  DELETE_RULE,
  TABLE_NAME,
  REFERENCED_TABLE_NAME
FROM information_schema.REFERENTIAL_CONSTRAINTS;


SELECT DISTINCT
  UPDATE_RULE,
  DELETE_RULE
FROM information_schema.REFERENTIAL_CONSTRAINTS;